apiVersion: v1
kind: Service
metadata:
  name: agno-assistant
  labels:
    app: agno-assistant
spec:
  type: ClusterIP
  ports:
    - port: 7777
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: agno-assistant
