apiVersion: v1
kind: Service
metadata:
  name: nats
  namespace: {{ project_namespace }}
  labels:
    app: nats
spec:
  type: ClusterIP
  ports:
    - port: 4222
      targetPort: client
      name: client
    - port: 6222
      targetPort: cluster
      name: cluster
    - port: 8222
      targetPort: monitor
      name: monitor
  selector:
    app: nats
---
# Headless service for StatefulSet DNS
apiVersion: v1
kind: Service
metadata:
  name: nats-headless
  namespace: {{ project_namespace }}
  labels:
    app: nats
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 4222
      targetPort: client
      name: client
    - port: 6222
      targetPort: cluster
      name: cluster
  selector:
    app: nats
