apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-api-python
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.middlewares: infrastructure-crowdsec-bouncer@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - dev.service.infatium.ru
      secretName: service-tls
  rules:
    - host: dev.service.infatium.ru
      http:
        paths:
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: app-auth-go
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app-api-go
                port:
                  number: 8080
