apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-integrations-python
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: infrastructure-security-headers@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - integrations.infatium.ru
      secretName: makefeed-integrations-tls
  rules:
    - host: integrations.infatium.ru
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app-integrations-go
                port:
                  number: 8000
