apiVersion: v1
kind: Service
metadata:
  name: makefeed-integrations
  namespace: infrastructure
  labels:
    app: makefeed-integrations
spec:
  selector:
    app: makefeed-integrations
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      name: http
  type: ClusterIP
