apiVersion: v1
kind: ConfigMap
metadata:
  name: app-integrations-go-config
data:
  HOST: "0.0.0.0"
  PORT: "8000"
  DEBUG: "false"
  OTEL_ENABLED: "true"
  OTEL_SERVICE_NAME: "makefeed-integrations-go"
  OTEL_EXPORTER_ENDPOINT: "tempo.grafana.svc.cluster.local:4317"
  OTEL_ENVIRONMENT: "production"
  METRICS_PORT: "9464"
  ENVIRONMENT: "production"
