apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-integrations-go
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - integrations-go.infra.makekod.ru
      secretName: makefeed-integrations-go-tls
  rules:
    - host: integrations-go.infra.makekod.ru
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app-integrations-go
                port:
                  number: 8000
