apiVersion: v1
kind: Service
metadata:
  name: worker-processor-go
  labels:
    app: worker-processor-go
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
    - port: 9464
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app: worker-processor-go
