apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgresql.yml
  - postgres-init.yml
  - postgres-init-user-job.yml
  - postgres-init-grafana-user-job.yml
  - grafana-postgres-sealed-secret.yml
  - telegram-media-cleanup-cronjob.yml
