apiVersion: v1
kind: ConfigMap
metadata:
  name: go-scraper-config
data:
  CRAWL4AI_URL: "http://crawl4ai:11235"
  DATABASE_URL: "postgres://scrapers:scrapers@postgres:5432/scrapers?sslmode=disable"
  SCRAPE_INTERVAL: "30m"
