apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-agents-python
  labels:
    app: worker-agents-python
    service-template: worker-python
    service-type: worker
    proxy-sidecar: enabled
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: worker-agents-python
  template:
    metadata:
      labels:
        app: worker-agents-python
        proxy-sidecar: enabled
    spec:
      nodeSelector:
        node-role: infra
      tolerations:
        - key: node-role
          operator: Equal
          value: infra
          effect: NoSchedule
      imagePullSecrets:
        - name: regcred
      containers:
        - name: worker-agents-python
          image: docker-registry.infrastructure:5000/makefeed-agents:dev
          imagePullPolicy: Always
          command: ["infatium-agents"]
          ports:
            - containerPort: 9464
              name: metrics
          envFrom:
            - configMapRef:
                name: worker-agents-python-config
            - secretRef:
                name: service-secrets
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 10"]
          resources:
            requests:
              cpu: 20m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 1Gi
      terminationGracePeriodSeconds: 30
