apiVersion: apps/v1
kind: Deployment
metadata:
  name: makefeed-registry
  labels:
    app: makefeed-registry
    service-type: worker
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: makefeed-registry
  template:
    metadata:
      labels:
        app: makefeed-registry
    spec:
      nodeSelector:
        node-role: infra
      tolerations:
        - key: node-role
          operator: Equal
          value: infra
          effect: NoSchedule
      imagePullSecrets:
        - name: regcred
      containers:
        - name: makefeed-registry
          image: docker-registry.infrastructure:5000/makefeed-service:latest
          imagePullPolicy: Always
          command: ["makefeed-registry"]
          envFrom:
            - configMapRef:
                name: registry-config
            - secretRef:
                name: service-secrets
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 10"]
          resources:
            requests:
              cpu: 10m
              memory: 192Mi
            limits:
              cpu: 200m
              memory: 256Mi
      terminationGracePeriodSeconds: 30
