apiVersion: v1
kind: ConfigMap
metadata:
  name: matomo-proxy-config
  namespace: infrastructure
data:
  proxy-config.ini: |
    [General]
    proxy_client_headers[] = "HTTP_X_FORWARDED_FOR"
    proxy_client_headers[] = "HTTP_X_REAL_IP"
    proxy_host_headers[] = "HTTP_X_FORWARDED_HOST"
    assume_secure_protocol = 1
    force_ssl = 1
