---
all:
  children:
    infra_nodes:
      hosts:
        infra-server:
          ansible_host: "{{ lookup('env', 'INFRA_SSH_HOST') }}"
          ansible_user: "{{ lookup('env', 'INFRA_SSH_USER') | default('root', true) }}"
          ansible_ssh_private_key_file: "{{ lookup('env', 'INFRA_SSH_KEY') | default('~/.ssh/id_rsa', true) }}"

    apps_nodes:
      hosts:
        # Add apps nodes here
        # Example:
        # apps-node-1:
        #   ansible_host: "{{ lookup('env', 'APPS_SSH_HOST') }}"
        #   ansible_user: "{{ lookup('env', 'APPS_SSH_USER') | default('root', true) }}"
        #   ansible_ssh_private_key_file: "{{ lookup('env', 'APPS_SSH_KEY') | default('~/.ssh/id_rsa', true) }}"
        #   product_name: "{{ lookup('env', 'PRODUCT_NAME') }}"
