apiVersion: v1
kind: Secret
metadata:
  name: SERVICE_NAME-secrets
type: Opaque
stringData:
  DATABASE_URL: "postgresql+asyncpg://postgres:PASSWORD@postgres.infatium-dev.svc.cluster.local:5432/postgres"

  AI_API_KEY: ""

  TELEGRAM_API_ID: ""
  TELEGRAM_API_HASH: ""
  TELEGRAM_PHONE: ""

  SUPABASE_KEY: ""
  SUPABASE_JWT_SECRET: ""

  API_KEY: ""
  PUBLIC_API_KEY: ""

  LANGFUSE_PUBLIC_KEY: ""
  LANGFUSE_SECRET_KEY: ""

  RUSTORE_WEBHOOK_AES_KEY_PRODUCTION: ""
  RUSTORE_WEBHOOK_AES_KEY_SANDBOX: ""
  RUSTORE_KEY_ID: ""

data:
  rustore_private_key.pem: ""
