apiVersion: v1
kind: Service
metadata:
  name: SERVICE_NAME
  labels:
    app: SERVICE_NAME
spec:
  selector:
    app: SERVICE_NAME
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: 8000
