apiVersion: v1
kind: Service
metadata:
  name: app-registry-go
  labels:
    app: app-registry-go
spec:
  selector:
    app: app-registry-go
  ports:
    - name: http
      port: 8080
      targetPort: http
    - name: metrics
      port: 9464
      targetPort: metrics
