apiVersion: v1
kind: Service
metadata:
  name: worker-poller-go
  labels:
    app: worker-poller-go
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      name: http
    - port: 9464
      targetPort: 9464
      name: metrics
  selector:
    app: worker-poller-go
