apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-web-python
  labels:
    app: worker-web-python
    service-template: worker-python
    service-type: worker
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: worker-web-python
  template:
    metadata:
      labels:
        app: worker-web-python
    spec:
      nodeSelector:
        node-role: infra
      tolerations:
        - key: node-role
          operator: Equal
          value: infra
          effect: NoSchedule
      imagePullSecrets:
        - name: regcred
      containers:
        - name: worker-web-python
          image: docker-registry.infrastructure:5000/makefeed-service:latest
          imagePullPolicy: Always
          command: ["makefeed-web"]
          envFrom:
            - configMapRef:
                name: worker-web-python-config
            - secretRef:
                name: service-secrets
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 10"]
          resources:
            requests:
              cpu: 10m
              memory: 192Mi
            limits:
              cpu: 500m
              memory: 512Mi
      terminationGracePeriodSeconds: 30
