apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-landing-typescript
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - dev.infatium.ru
      secretName: landing-dev-tls
  rules:
    - host: dev.infatium.ru
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app-landing-typescript
                port:
                  number: 3000
