name: Build & Deploy go-poller

on:
  push:
    branches: [develop, master]
    paths:
      - 'services/go-poller/**'
      - '.github/workflows/ci-go-poller.yml'
      - '.github/workflows/ci-go-ko.yml'

jobs:
  build-and-deploy:
    uses: ./.github/workflows/ci-go-ko.yml
    with:
      service-name: go-poller
      service-path: services/go-poller
      import-path: ./cmd/poller
      image-name: go-poller
      deployment-name: worker-poller-go
      namespace: ${{ github.ref == 'refs/heads/master' && 'infatium-prod' || 'infatium-dev' }}
      image-tag: ${{ github.ref == 'refs/heads/master' && 'prod' || 'dev' }}
    secrets: inherit
