name: Build & Deploy go-registry

on:
  push:
    branches: [develop]
    paths:
      - 'services/go-registry/**'
      - '.github/workflows/ci-go-registry.yml'
      - '.github/workflows/ci-go-ko.yml'

jobs:
  build-and-deploy:
    uses: ./.github/workflows/ci-go-ko.yml
    with:
      service-name: go-registry
      service-path: services/go-registry
      import-path: ./cmd/registry
      image-name: go-registry
      deployment-name: app-registry-go
      namespace: infatium-dev
    secrets: inherit
