name: Build & Deploy go-processor

on:
  push:
    branches: [develop, master]
    paths:
      - 'services/go-processor/**'
      - '.github/workflows/ci-go-processor.yml'
      - '.github/workflows/ci-go-ko.yml'

jobs:
  build-and-deploy:
    uses: ./.github/workflows/ci-go-ko.yml
    with:
      service-name: go-processor
      service-path: services/go-processor
      import-path: ./cmd/processor
      image-name: go-processor
      deployment-name: worker-processor-go
      namespace: ${{ github.ref == 'refs/heads/master' && 'infatium-prod' || 'infatium-dev' }}
      image-tag: ${{ github.ref == 'refs/heads/master' && 'prod' || 'dev' }}
    secrets: inherit
