name: Build & Deploy go-api

on:
  push:
    branches: [develop]
    paths:
      - 'services/go-api/**'
      - '.github/workflows/ci-go-api.yml'
      - '.github/workflows/ci-go-ko.yml'

jobs:
  build-and-deploy:
    uses: ./.github/workflows/ci-go-ko.yml
    with:
      service-name: go-api
      service-path: services/go-api
      import-path: ./cmd/api
      image-name: go-api
      deployment-name: app-api-go
      namespace: infatium-dev
    secrets: inherit
