name: Build & Deploy go-processor

on:
  push:
    branches: [develop]
    paths:
      - 'services/go-processor/**'
      - '.github/workflows/ci-go-processor.yml'
      - '.github/workflows/ci-go-ko.yml'

jobs:
  build-and-deploy:
    uses: ./.github/workflows/ci-go-ko.yml
    with:
      service-name: go-processor
      service-path: services/go-processor
      import-path: ./cmd/processor
      image-name: go-processor
      deployment-name: worker-processor-go
      namespace: infatium-dev
    secrets: inherit
