name: Build & Deploy go-poller

on:
  push:
    branches: [develop]
    paths:
      - 'services/go-poller/**'
      - '.github/workflows/ci-go-poller.yml'
      - '.github/workflows/ci-go-ko.yml'

jobs:
  build-and-deploy:
    uses: ./.github/workflows/ci-go-ko.yml
    with:
      service-name: go-poller
      service-path: services/go-poller
      import-path: ./cmd/poller
      image-name: go-poller
      deployment-name: worker-poller-go
      namespace: infatium-dev
    secrets: inherit
