name: Build & Deploy go-scraper

on:
  push:
    branches: [develop]
    paths:
      - 'services/go-scraper/**'
      - '.github/workflows/ci-go-scraper.yml'
      - '.github/workflows/ci-go-ko.yml'

jobs:
  build-and-deploy:
    uses: ./.github/workflows/ci-go-ko.yml
    with:
      service-name: go-scraper
      service-path: services/go-scraper
      import-path: ./cmd/scraper
      image-name: go-scraper
      deployment-name: go-scraper
      namespace: scrapers-dev
    secrets: inherit
